### ISSUE TITLE
Cleanup repository

### ISSUE THREAD

**Issue by thiagomael** [SPLMC/reana-spl#15]
As developers, we need an organized code base to work in, to enable software maintenance and evolution.

**Comment by thiagomael** [comment]
I understand that @andrelanna accepted @brenoafb 's implementation of feature-family-product-based analysis, right? So, I closed the open pull requests (all of which were related to that).

**Comment by thiagomael** [comment]
@andrelanna, @tobiassena, @brenoafb: out of the existing branches, it seems to me that `addPersistence` can be deleted. Is that so?

**Comment by thiagomael** [comment]
@andrelanna, @tobiassena, @brenoafb:
can we incorporate the changes from `ddsPersistence-Andre` into `reanaE`, so that we have a single branch to fresh-start? Like an "unstable master"/"development branch".

**Comment by tobiassena** [comment]
I think there are two different approaches that we still need to discuss. However, the problem of cudd is the same.

**Comment by thiagomael** [comment]
> I think there are two different approaches that we still need to discuss. However, the problem of cudd is the same.

Ok, this is a place for asynchronous discussion. :)
What is the problem to which these two approaches apply? And what are the approaches themselves?

**Comment by brenoafb** [comment]
> @andrelanna, @tobiassena, @brenoafb:
> can we incorporate the changes from `ddsPersistence-Andre` into `reanaE`, so that we have a single branch to fresh-start? Like an "unstable master"/"development branch".

Seems like a good idea to me, since this branch doesn't really implement any major change in functionality. Maybe we can use it as a testing ground for minor or experimental persistence-related changes?

**Comment by thiagomael** [comment]
@tobiassena, can you please elaborate on your objections to merging the branches?

**Comment by andrelanna** [comment]
> I understand that @andrelanna accepted @brenoafb 's implementation of feature-family-product-based analysis, right? So, I closed the open pull requests (all of which were related to that).

Yes, that's right!

**Comment by tobiassena** [comment]
> @tobiassena, can you please elaborate on your objections to merging the branches?

ReanaE and ddsPersistence-Andre treat the content of persistence differently when making the analysis, I don't see how to merge FeatureFamilyBasedAnalyzer.java and Component.java.

**Comment by thiagomael** [comment]
> > @tobiassena, can you please elaborate on your objections to merging the branches?
> 
> ReanaE and ddsPersistence-Andre treat the content of persistence differently when making the analysis, I don't see how to merge FeatureFamilyBasedAnalyzer.java and Component.java.

As far as I understand the ongoing development, `ddsPersistence-Andre` has the single purpose of implementing DD persistence, whereas `reanaE` is a prototypical evolution-aware tool. The persistence-related code in `reanaE` should then be discarded in favor of the one coming from `ddsPersistence-Andre`, and the evolution-aware analysis in the latter branch should be replaced by the one implemented in the former.

Am I right? Also, @andrelanna and @brenoafb, what do you think?

**Comment by andrelanna** [comment]
That's it, @thiagomael! While @brenoafb and I tried to implement the methods for ADDs persistence (including understanding and solving the persistence problem we are facing nowadays), @tobiassena and Danilo worked on an evolution-aware analysis method.

**Comment by thiagomael** [comment]
Guys, I think this task blocks #19. However, #20 can be handled simultaneously.

**Comment by brenoafb** [comment]
The `ddsPersistence-Andre` branch was meant to test ADD persistence in the context of the analysis, so the code doesn't belong in the `ReanaE` branch. Therefore it can be safely removed.
Same goes for `addPersistence`.
