### ISSUE TITLE
Automate iteration over evolutions

### ISSUE THREAD

**Issue by thiagomael** [SPLMC/reana-spl#18]
To test our implementation, we are manually changing code and recompiling.
We need to automate this process, possibly by exposing the variables to be changed as CLI arguments and using a script that cleans up the environment and then iteratively calls ReAna.

**Comment by thiagomael** [comment]
@tobiassena, can you handle this one?

**Comment by tobiassena** [comment]
> @tobiassena, can you handle this one?

Ok

**Comment by tobiassena** [comment]
v1 done
