### ISSUE TITLE
Define a CLI for calling ReAna with evolution-aware analysis capabilities

### ISSUE THREAD

**Issue by thiagomael** [SPLMC/reana-spl#20]
We need a command-line interface to tell ReAna to execute our evolution-aware algorithm. At the moment, we will probably also need to provide the actual evolution step being analyzed, since we currently lack impact analysis.

This is a dependency for parallel development of #18 and #19.

**Comment by andrelanna** [comment]
The script for performing evolution-aware analysis is ready. The file evolutionAwareAnalysis.sh contains the script and it is variable according to the following parameters: 
- Spl name
- initial evolution (seed for the analysis)
- final evolution
- number of iterations 
- initial and maximum memory pool for JVM.
